- hosts: localhost
  tasks:
  - name: "{{ tower_job_template_name }}"
    na_ontap_info:
      state: info
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: "{{ https }}"
      validate_certs: "{{ validate_certs }}"
    register: netapp
  - debug:
      msg: "{{ netapp.ontap_info.cluster_node_info }}"
