- hosts: localhost
  collections:
    - netapp.ontap
  tasks:
  - name: "{{ tower_job_template_name }}"
    na_ontap_info:
      state: info
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: "{{ https }}"
      validate_certs: false
      gather_subset:
        - ontap_system_version
    register: netapp
  - debug:
      msg: "{{ netapp.ontap_info }}"
