- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    na_input: &na_input
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  tasks:
  - name: ONTAP software update
    na_ontap_software_update:
      <<: *na_input
      state: present
      package_url: "{{ package_url }}"
      package_version: "{{ version_name }}"
      ignore_validation_warning: True
      download_only: "{{ download_only }}"
    register: output
  - debug: var=output  
