- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    na_input: &na_input
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      volume: "qtreetest"
      qtree: "testqtree"
      https: true
      validate_certs: false
      use_rest: "Always"
  tasks:
  - name: Create Qtree
    na_ontap_qtree:
      state: present
      name: testqtree
      flexvol_name: qtreetest
      export_policy: qtreetestpolicy
      security_style: ntfs
      vserver: storage2
      <<: *na_input
      
  - name: "Clone export export_policy.name"
    block:
      - name: Create Export Policy
        na_ontap_export_policy:
          state: present
          name: "{{ volume }}.{{ qtree }}"
          vserver: "{{ vserver }}"
          <<: *auth
          
      - name: Get info from existing policy
        netapp.ontap.na_ontap_rest_info:
            gather_subset:
              - export_policy_info
            parameters:
              name: "{{ export_policy }}"
              svm.name: "{{ vserver }}"
            fields:
              - 'rules'
            <<: *auth
        register: export_policy_info
      - set_fact:
          export_policy_rules: "{{ export_policy_info.ontap_info['protocols/nfs/export-policies'].records[0].rules }}"
          
      - name: Create rule
        netapp.ontap.na_ontap_export_policy_rule:
          state: present
          name: "{{ volume }}.{{ qtree }}"
          vserver: "{{ vserver }}"
          client_match: "{{ item | json_query('clients[*].match') }}"
          ro_rule: "{{ item.ro_rule }}"
          rw_rule: "{{ item.rw_rule }}"
          protocol: "{{ item.protocols }}"
          super_user_security: "{{ item.superuser }}"
          anonymous_user_id: "{{ item.anonymous_user }}"
          allow_suid: "{{ item.allow_suid }}"
          <<: *auth
        loop: "{{ export_policy_rules }}"

      - name: "Apply new policy to qtree"
        na_ontap_qtree:
          state: present
          name: "{{ qtree }}"
          flexvol_name: "{{ volume }}"
          vserver: "{{ vserver }}"
          export_policy: "{{ volume }}.{{ qtree }}"
          <<: *auth

      - set_fact:
          export_policy: "{{ volume }}.{{ qtree }}"

