- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars:
    na_input: &na_input
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      source-path: "{{ source-path }}"
      https: true
      validate_certs: false
  tasks:
  - name: Attempt to Update LS Mirror
    na_ontap_zapit:
      <<: *na_input
      vserver: test
      zapi:
        snapmirror-update-ls-set:
          source-location: source-path
    register: output
  - debug: var=output